<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="Stylesheet" type="text/css" href="style\main.php" />
<script type="text/javascript" src="js/prototype.js"></script>
<script type="text/javascript" src="js/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="js/lightbox.js"></script>
<script type="text/javascript" src="js/wnioski_calendar.js"></script>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" language="javascript" src="TableFilter/tablefilter_all.js"></script>  
<!-- <link rel=stylesheet type=text/css href=/Strona/style.css> -->
<link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" /> 
<LINK REL="SHORTCUT ICON" HREF="img\intranet_s.ico">
<title>RPWiK - Intranet</title>
</head>
<body>